# Generated by Django 6.0.2 on 2026-02-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_venta_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorindustrial',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='LecturaSensor',
        ),
        migrations.DeleteModel(
            name='SensorIndustrial',
        ),
    ]
